name: Bug Report
description: Bug observed in oracle-guardian-ai library
title: "[Bug]: "
labels: [Bug, Backlog]

body:
  - type: markdown
    attributes:
      value: |
        If you think you've found a security vulnerability, don't raise a GitHub issue and follow the instructions
        in our [security policy](https://github.com/oracle/guardian-ai/security/policy).

        ---

        Thank you for taking the time to file a bug report.
  - type: checkboxes
    id: checks
    attributes:
      label: oracle-guardian-ai version used
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the
            [latest version](https://github.com/oracle/guardian-ai/releases) of oracle-guardian-ai.
        - label: >
            I have confirmed this bug exists on the main branch of oracle-guardian-ai.
        - label: >
            I agree to follow the [Code of Conduct](https://github.com/oracle/.github/blob/main/CODE_OF_CONDUCT.md).
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Please provide a brief description of the problem, describe setup used as that may be the key to the issue.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to Reproduce
      description: >
        Please provide a copy-pastable short code example.
        If possible provide an ordered list of steps on how to reproduce the problem.
      placeholder: >
        mlflow deployments help -t oci-datascience

        ...
      render: python
    validations:
      required: true
  - type: textarea
    id: what-was-observed
    attributes:
      label: What was Observed
      description: >
        Please provide snippets of output or describe wrong behavior.
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What was Expected
      description: >
        Please describe what should have happened and how it is different from what was observed.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: >
        Please paste the output of ``pip freeze | grep guardian_ai``
      value: >
        <details>

        Paste here the output of ``pip freeze | grep guardian_ai``

        </details>
    validations:
      required: true